### ISSUE TITLE
INVALID: Open up browser immediately after running the script 

### ISSUE THREAD

**Issue by edrisranjbar** [edrisranjbar/AparatDownloader#5]
right now, after running the script, it's going to open a new chrome browser with an empty tab; which is not good at all. because the user looses focus from GUI app. so we need to open browser after user clicks download.
**This way user stays focused on what his going to do.**

**Comment by devgdr** [comment]
سلام 
شرمنده حوصله پول رکوست نداشتم 
```python
options = webdriver.ChromeOptions()
options.add_experimental_option("excludeSwitches", ["enable-logging"])
options.add_argument('headless')
```
این مشکلت رو حل میکنه.
برای لینک گرفتن هم برنامت مشکل داره که:
```python
driver.switch_to.window(driver.window_handles[-1])
```
هندل میکنه 
من قبلا یه برنامه کامل برای اپارت نوشته بودم روزگار گشت چند بار پاک شد حتی جادی تو یکی ازبرنامه هاش معرفیش کرد خیلی استفبالم ازش شد  تا چند روز پیش راهم باز به اپارات افتاد 
از اونجا که برنامه از کار افتاده بود برنامه تو رو دیدم (هم زمان داشتم روی برنامه خودم کار میکردم که خیلی این دوتا کمکم کردن 
```
"#primary > div.single-details > div.single-details__info > div.single-details__utils > div > div > div.download-button > div > div > button"
"a.titled-link.title[data-refer=playlists]"
```
بخصوص دومی گفتم ادای دینی باشه =)
لینک برنامه خودم 
اگه پول رکوئستی داشتی خوشحال میشم مرجش کنم =)
راستی رو pypiهست 
[لینک ](https://github.com/mehdigdr/aparat-dl)

**Comment by edrisranjbar** [comment]
Thanks to @mehdigdr this issue is done ✅
